config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  get 'home/index'

  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :articles
  root 'home#index'

  get 'home/about' => 'home#about'

  Rails.application.routes.draw do
  get 'users/new'

    get    '/help',    to: 'static_pages#help'
    get    '/about',   to: 'static_pages#about'
    get    '/contact', to: 'static_pages#contact'
    get    '/signup',  to: 'users#new'
    post   '/signup',  to: 'users#create'
    get    '/signin',   to: 'sessions#new'
    post   '/signin',   to: 'sessions#create'
    delete '/signout',  to: 'sessions#destroy'
    resources :users
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :title, presence: true
  validates :text, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include SessionsHelper
  protect_from_forgery with: :exception

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end
  # helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def index
    @articles = current_user.articles
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in (user)
      redirect_back_or user
    else
      flash[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def login(user)
    session[:user_id] = user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in (@user)
      flash[:success] = "Welcome to the Clean Note App"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # def signed_in_user
  #   redirect_to signin_url, notice: "Please sign in." unless signed_in?
  # end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/articles/edit.html.erb
<div class="new article col-md-6 col-md-offset-3 custom">
  <h2>
    Edit your note:
  </h2>
  <div class="well">

    <%= form_for :article, url: article_path(@article), method: :patch do |f| %>
        <% if @article.errors.any? %>
            <div id="error_explanation">
              <h3>
                <%= pluralize(@article.errors.count, "error") %> prohibited
                this article from being saved:
              </h3>
              <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <p>
          <%= f.label "Enter your title" %><br>
          <%= f.text_field :title, :class => "form-control" %>
        </p>

        <p>
          <%= f.label "Enter your description" %><br>
          <%= f.text_area :text, :class => "form-control", :rows => "10" %>
        </p>

        <p>
        <ul class="pager">
          <li class="center">


            <%= f.submit "Submit", :class=> "btn btn-primary" %>

            <%= link_to 'Back', articles_path %>
          </li>
        </ul>
        </p>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<html>

<body>
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 custom">
      <h1>Listing articles</h1>
      <hr>

      <% @articles.each do |article| %>
          <div class="post-preview">
            <a href="#">
              <h2 class="post-title">
                <%= article.title %>
              </h2>
              <h3 class="post-subtitle">
                <%= article.text %>
              </h3>
            </a>
            <p class="post-meta">Posted by <a href="#">Rafiq</a> <%= article.created_at %></p>
            <ul class="pager">
              <li class="next">
                <%= link_to 'Destroy', article_path(article),
                            method: :delete,
                            data: {confirm: 'Are you sure?'} %>
                <%= link_to 'Show', article_path(article) %>
                <%= link_to 'Edit', edit_article_path(article) %>
              </li>
            </ul>
          </div>
          <hr>
      <% end %>
      <!-- Pager -->
      <ul class="pager">
        <li class="next">
          <a href="#">Older Posts &rarr;</a>
        </li>
      </ul>

    </div>
  </div>
</div>
</body>
</html>

app/views/articles/new.html.erb
<div class="new article col-md-6 col-md-offset-3 custom">
  <h2>
    Create your Note here:
  </h2>
  <div class="well">

    <%= form_for :article, url: articles_path do |f| %>
        <% if @article.errors.any? %>
            <div id="error_explanation">
              <h3>
                <%= pluralize(@article.errors.count, "error") %> prohibited
                this article from being saved:
              </h3>
              <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <p>
          <%= f.label "Enter your title" %><br>
          <%= f.text_field :title, :class => "form-control" %>
        </p>

        <p>
          <%= f.label "Enter your description" %><br>
          <%= f.text_area :text, :class => "form-control", :rows => "10" %>
        </p>

        <p>
        <ul class="pager">
          <li class="center">


            <%= f.submit "Submit", :class=> "btn btn-primary" %>

            <%= link_to 'Back', articles_path %>
          </li>
        </ul>
        </p>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<html lang="en">
<body>
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 custom">
      <h1><%= @article.title %></h1>
      <hr>
      <div class="post-preview">
        <h3 class="post-subtitle">
          <i><%= @article.text %></i>
        </h3>
        <ul class="pager">
          <li class="next">
          </li>
        </ul>
      </div>
      <hr>
      <!-- Pager -->
      <ul class="pager">
        <li class="next">
          <%= link_to 'Back', articles_path  %>
        </li>
      </ul>

    </div>
  </div>
</div>
</body>
</html>

app/views/home/about.html.erb
<script>
  $(".navbar-default").css({ 'background-color' : 'transparent' });
</script>

<html lang="en">
<body>

<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('http://www.emotionalbalance.com.au/wp-content/uploads/2014/07/Man-in-Shadow.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="page-heading">
          <h1>About Me</h1>
          <hr class="small">
          <span class="subheading">This is what I do.</span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit,
        fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto
        error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas
        voluptatibus, minus!</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui
        voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi!
        Et.</p>
    </div>
  </div>
</div>

<hr>

<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <p class="copyright text-muted">Copyright &copy; Clean Notepad 2017</p>
      </div>
    </div>
  </div>
</footer>

</body>

</html>

app/views/home/index.html.erb
<script>
  $(".navbar-default").css({ 'background-color' : 'transparent' });
</script>

<div class="intro-header" style="background-image: url('https://i.imgur.com/5R2VDkH.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>Clean Notepad</h1>
          <hr class="small">
          <span class="subheading">Discover what a new kind of note can do for you.</span>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <h1>Hello, Rails! This is my Rails Application</h1>
      <hr>
      <!-- Pager -->
      <ul class="pager">
        <li class="center">
          <%= link_to 'Create', new_article_path %>
          <%= link_to 'All Articles', controller: 'articles' %>
        </li>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!--<link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


<!DOCTYPE html>
<html>
<head>
  <title>Notepad</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> custom"><%= message %></div>
<% end %>

<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">

    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="#">Clean Notepad</a>
    </div>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "About", home_about_path %>
        </li>
        <li>
          <a href="#">Sample Post</a>
        </li>
        <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>

           <li> <%= link_to "Sign out", signout_path, :method => :delete %> </li>
        <% else %>
            <li>
              <%= link_to "SignIn", signin_path %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 custom">

    <% provide(:title, "Edit user") %>
    <h1>Update your profile</h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
      <li>
        <%= link_to user.id, user %>
        <%= link_to user.name, user %>
        <%= link_to user.email, user %>
      </li>
      <% if current_user.admin? && !current_user?(user) %>
          | <%= link_to "delete", user, method: :delete,
                        data: { confirm: "You sure?" } %>
      <% end %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 custom">
    <% provide(:title, 'Sign up') %>
    <h1>Sign up</h1>

    <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row custom">
      <h1>
        <%= @user.name %>
      </h1>
</div>